minorVersion: 0
majorVersion: 0
patchVersion: 1
releaseVersionString: '$(majorVersion).$(minorVersion).$(patchVersion)'

prereleaseFix: 'build'
prereleaseNumber: '$()-$(github.run_number)'
prereleaseVersionString: '$(majorVersion).$(minorVersion).$(patchVersion)-$(prereleaseFix)$(prereleaseNumber)'