minorVersion: 0
majorVersion: 0
patchVersion: 1
prereleaseFix: 'build'
prereleaseNumber: '$()-$(github.run_number)'
releaseVersionString: '$(majorVersion).$(minorVersion).$(patchVersion)'
prereleaseVersionString: '$(majorVersion).$(minorVersion).$(patchVersion)-$(prereleaseFix)$(prereleaseNumber)'