name: Build, Test, Pack, and Publish NuGet Release Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest       

    steps:    
    - name: Check Out Source Code
      uses: actions/checkout@v4

    - name: Read YAML File
      uses: pietrobolcato/action-read-yaml@1.0.0
      id: read
      with:
        config: ${{ github.workspace }}/.github/variables.yaml

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Specify your .NET version here

    - name: Restore Project Dependencies
      run: dotnet restore

    - name: Build Restored Project
      run: dotnet build --no-restore --configuration Release

    - name: Test Built Project
      run: dotnet test --no-build --no-restore --configuration Release

    - name: Pack NuGet Package
      run: dotnet pack --no-build --no-restore --configuration Release --output ./nupkg /p:PackageVersion=${{ steps.read.outputs['releaseVersionString'] }}
      
    - name: Publish NuGet Package
      run: dotnet nuget push ./nupkg/${{ github.workspace }}.${{ steps.read.outputs['releaseVersionString'] }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
