name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  read-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Code
      uses: actions/checkout@v4
  
    - name: Load Version Variables
      uses: './.github/version.yaml'

  build:
    runs-on: windows-latest       

    steps:    
    - name: Check Out Source Code
      uses: actions/checkout@v4

    - name: Read YAML File
      uses: pietrobolcato/action-read-yaml@1.0.0
      id: read_action_js
      with:
        config: ${{ github.workspace }}/.github/variables.yaml'      
    
    - name: TOOST
      run: echo "${{ version.versionString }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Specify your .NET version here

    - name: Restore Project Dependencies
      run: dotnet restore

    - name: Build Restored Project
      run: dotnet build --no-restore

    - name: Test Built Project
      run: dotnet test --no-build --no-restore

    - name: Pack NuGet Package
      run: dotnet pack --no-build --no-restore --configuration Release --output ./nupkg /p:PackageVersion=${{ version.majorVersion }}.${{ version.minorVersion }}.${{ version.patchVersion }}
      
    - name: Publish NuGet Package
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
